require 'rest-client'
require 'json'
require 'net/http'
require File.dirname(__FILE__) + '/proxmox-rb/auth'
require File.dirname(__FILE__) + '/proxmox-rb/cluster_resources'
require File.dirname(__FILE__) + '/proxmox-rb/qemu_kvm'
